[repository]
repository = "opendal:webdav"
password = "my-backup-password"

[repository.options]
endpoint = "https://my-owncloud-server.com"
root = "remote.php/webdav/my-folder"
username = "owncloud-user"
password = "owncloud-passcode"
